#if !defined(RULES_H)
#define RULES_H

#define R_FILE 0
#define R_PACKAGE 1
#define R_IMPORTS 2
#define R_IMPORT 3
#define R_IMPORT_STMT 4
#define R_IMPORT_STMT_LIST 5
#define R_IMPORT_HERE 6
#define R_IMPORT_PACKAGE 7
#define R_IMPORT_SAFETY 8
#define R_XDCL 9
#define R_COMMON_DCL 10
#define R_LCONST 11
#define R_VARDCL 12
#define R_CONSTDCL 13
#define R_CONSTDCL1 14
#define R_TYPEDCLNAME 15
#define R_TYPEDCL 16
#define R_SIMPLE_STMT 17
#define R_COMPOUND_STMT 18
#define R_LOOP_BODY 19
#define R_FOR_HEADER 20
#define R_FOR_BODY 21
#define R_FOR_STMT 22
#define R_IF_HEADER 23
#define R_IF_STMT 24
#define R_ELSEIF 25
#define R_ELSEIF_LIST 26
#define R_ELSE 27
#define R_EXPR 28
#define R_UEXPR 29
#define R_PSEUDOCALL 30
#define R_PEXPR_NO_PAREN 31
#define R_START_COMPLIT 32
#define R_KEYVAL 33
#define R_BARE_COMPLITEXPR 34
#define R_COMPLITEXPR 35
#define R_PEXPR 36
#define R_EXPR_OR_TYPE 37
#define R_NAME_OR_TYPE 38
#define R_LBRACE 39
#define R_NEW_NAME 40
#define R_DCL_NAME 41
#define R_SYM 42
#define R_HIDDEN_IMPORTSYM 43
#define R_NAME 44
#define R_LABELNAME 45
#define R_DOTDOTDOT 46
#define R_NTYPE 47
#define R_NON_EXPR_TYPE 48
#define R_CONVTYPE 49
#define R_COMPTYPE 50
#define R_FNRET_TYPE 51
#define R_DOTNAME 52
#define R_OTHERTYPE 53
#define R_PTRTYPE 54
#define R_STRUCTTYPE 55
#define R_XFNDCL 56
#define R_FNDCL 57
#define R_FNTYPE 58
#define R_FNBODY 59
#define R_FNRES 60
#define R_FNLITDCL 61
#define R_FNLITERAL 62
#define R_XDCL_LIST 63
#define R_VARDCL_LIST 64
#define R_CONSTDCL_LIST 65
#define R_TYPEDCL_LIST 66
#define R_STRUCTDCL_LIST 67
#define R_STRUCTDCL 68
#define R_PACKNAME 69
#define R_EMBED 70
#define R_ARG_TYPE 71
#define R_ARG_TYPE_LIST 72
#define R_OARG_TYPE_LIST_OCOMMA 73
#define R_STMT 74
#define R_NON_DCL_STMT 75
#define R_STMT_LIST 76
#define R_NEW_NAME_LIST 77
#define R_DCL_NAME_LIST 78
#define R_EXPR_LIST 79
#define R_EXPR_OR_TYPE_LIST 80
#define R_KEYVAL_LIST 81
#define R_BRACED_KEYVAL_LIST 82
#define R_OSEMI 83
#define R_OCOMMA 84
#define R_OEXPR 85
#define R_OEXPR_LIST 86
#define R_OSIMPLE_STMT 87
#define R_OLITERAL 88

#endif // RULES_H
